### ISSUE TITLE
Supress messages for blocks when used for commands

### ISSUE THREAD

**Issue by kencinder** [TechnicJelle/SimpleBlockCommands#6]
eg; when using a bed for commands, and it's daytime you will get the "You can only sleep at night or during a thunderstorm" message.

**Comment by TechnicJelle** [comment]
Perhaps a useful link: https://www.spigotmc.org/threads/is-it-possible-to-change-the-you-cannot-sleep-at-day-actionbar-message.393765/

**Comment by TechnicJelle** [comment]
Mainly this: https://papermc.io/javadocs/paper/1.18/org/bukkit/event/player/PlayerInteractEvent.html#setCancelled(boolean)
